### PR TITLE
Update projects.vue, fix CustardMC

### PR DESCRIPTION
**Pull request by worldwidepixel**

### CODE REVIEW

**Comment by worldwidepixel** [comment]
pretty please merge

**Comment by blryface** [comment]
no fuck you

**Comment by worldwidepixel** [comment]
seems like I have changed their minds

**Comment by worldwidepixel** [comment]
please add forge support

**Comment by blryface** [comment]
blocked

**Comment by blryface** [comment]
wait holy shit this chat is live

**Comment by worldwidepixel** [comment]
it is!

**Comment by blryface** [comment]
image
or is it

**Comment by worldwidepixel** [comment]
why has so much effort gone into this chat

**Comment by worldwidepixel** [comment]
I don't need Github IRC

**Comment by blryface** [comment]
why not

**Comment by blryface** [comment]
true but this might be actually useful for actual devs developing things that are not us

**Pull request merged**
